--- 
ansible_user: sysadmin

satellite_systems:
  satellite: 
    vm_memory: 33554
    vm_vcpus: 4
    vm_osinfo_name: rhel9.7
    vm_mac_address: 52:54:00:da:2d:88
    vm_disk_size: 450
    vm_install_iso: "rhel-9.7-x86_64-dvd.iso"
    vm_kickstart_file: rhel9.7.ks
  server01: 
    vm_memory: 8192
    vm_vcpus: 2
    vm_osinfo_name: rhel10.1
    vm_mac_address: 52:54:00:3d:d0:56
    vm_disk_size: 50
    vm_install_iso: "rhel-10.1-x86_64-dvd.iso"
    vm_kickstart_file: rhel10.1.ks
  server02: 
    vm_memory: 8192
    vm_vcpus: 2
    vm_osinfo_name: rhel9.7
    vm_mac_address: 52:54:00:17:51:2f
    vm_disk_size: 35
    vm_install_iso: "rhel-9.7-x86_64-dvd.iso"
    vm_kickstart_file: rhel9.7.ks
    