---
version: 3
images:
  base_image:
    name: registry.fedoraproject.org/fedora:42 # registry.redhat.io/ansible-automation-platform-26/ee-minimal-rhel9:1.0 # registry.redhat.io/ubi9/ubi:latest
    options:
      pull_policy: missing
      tls_verify: false

dependencies:
  galaxy:
    collections:
      - { name: community.general, version: 10.3.0 }
      - { name: ansible.posix, version: 1.6.2 }
      - { name: redhat.insights, version: 1.3.0 }
      - { name: redhat.rhel_system_roles, version: 1.95.7 }
      - { name: redhat.satellite_operations, version: 3.0.0 }
      - { name: redhat.satellite, version: 5.3.0 }
      - { name: containers.podman, version: 1.16.3 }
      - { name: community.docker, version: 5.0.3 }
      - { name: redhat.runtimes_common, version: 1.2.2 }
      - name: community.libvirt
        type: git
        version: "main"
        source: https://github.com/ansible-collections/community.libvirt
  python:
    - pkgconfig
    - passlib
    - jmespath
    - hvac
    - paramiko 
    - pyOpenSSL 
    - netaddr 
    - lxml
    - libvirt-python
  system:
    - unzip [platform:redhat]
    - git [platform:redhat]
    - pkg-config [platform:redhat]
    - gcc [platform:redhat]
    - libvirt [platform:redhat]
    - libvirt-devel [platform:redhat]
    - python3.11-devel [platform:redhat]

  python_interpreter:
      package_system: "python311"
      python_path: "/usr/bin/python3.11"
  ansible_core:
    package_pip: ansible-core==2.16.15
  ansible_runner:
    package_pip: ansible-runner==2.3.6

additional_build_files:
  - src: ansible.cfg
    dest: configs

additional_build_steps:
  prepend_galaxy:
    # Copy ansible.cfg from build directory to EE
    - COPY _build/configs/ansible.cfg /etc/ansible/ansible.cfg
    - RUN $PKGMGR -y install git

options:
  package_manager_path: /usr/bin/microdnf
  tags:
      - quay.io/jerrycorum/compliance_ee:2.0
